source 'https://rubygems.org'
gem "bundler"
gem "jekyll"
gem "jekyll-paginate"
gem 'jekyll-tagging'
gem "jekyll-sitemap"
gem "jekyll-archives"
gem 'jekyll-target-blank'
gem 'jekyll-feed'
gem 'jekyll-seo-tag'